// Menu bar layout. Strings are command ids from commands.js; "-" is a separator.
export const MENUS = [
  {
    id: 'file',
    label: 'File',
    items: [
      'newProject',
      { label: 'New from Template', items: ['newBlank', 'newExample', '-', 'templates'] },
      'importZip',
      'openFolder',
      '-',
      'openProjects',
      { label: 'Recent Projects', dynamic: 'recent' },
      '-',
      'newFile',
      'newFolder',
      'uploadFiles',
      'zotero',
      '-',
      'save',
      'saveAll',
      '-',
      'downloadPdf',
      'exportZip',
      '-',
      'projectSettings',
      'openProjectFolder',
      '-',
      'closeProject',
      'exit',
    ],
  },
  {
    id: 'edit',
    label: 'Edit',
    items: ['undo', 'redo', '-', 'cut', 'copy', 'paste', 'selectAll', '-', 'find', 'projectSearch', 'gotoLine', '-', 'toggleComment', 'indentMore', 'indentLess', '-', 'addComment', '-', 'preferences'],
  },
  {
    id: 'insert',
    label: 'Insert',
    items: [
      { label: 'Heading', items: ['insChapter', 'insSection', 'insSubsection', 'insSubsubsection'] },
      '-',
      'insFigure',
      'insTable',
      '-',
      'insInlineMath',
      'insDisplayMath',
      'insEquation',
      'insAlign',
      '-',
      'insItemize',
      'insEnumerate',
      '-',
      'insCite',
      'zotero',
      'insRef',
      'insLabel',
      'insFootnote',
      'insLink',
      '-',
      'insSymbol',
      'insTOC',
      'insBibliography',
      'insPageBreak',
    ],
  },
  {
    id: 'format',
    label: 'Format',
    items: ['bold', 'italic', 'underline', 'emph', 'monospace', 'smallcaps', '-', 'fontLarge', 'fontSmall', 'alignCenter'],
  },
  {
    id: 'view',
    label: 'View',
    items: [
      'modeSource',
      'modeVisual',
      '-',
      { label: 'Layout', items: ['layoutSplit', 'layoutEditor', 'layoutPdf'] },
      '-',
      'toggleSidebar',
      'toggleOutline',
      'toggleSymbols',
      'toggleLogs',
      '-',
      { label: 'Theme', items: ['themeLight', 'themeDark', '-', 'themeSystem'] },
      'toggleTheme',
      'pdfDark',
      '-',
      'zoomIn',
      'zoomOut',
      'zoomReset',
      'fullscreen',
    ],
  },
  {
    id: 'tools',
    label: 'Tools',
    items: [
      'compile',
      'stopCompile',
      'compileDraft',
      'compileScratch',
      'clearCache',
      'autoCompile',
      { label: 'Compiler', items: ['compilerPdf', 'compilerXe', 'compilerLua'] },
      '-',
      'syncToPdf',
      '-',
      'checkPackages',
      'installPackage',
      'texDistribution',
      '-',
      'wordCount',
      'history',
      'git',
      'zotero',
      '-',
      'openOutput',
      'openPdfExternal',
      '-',
      'devtools',
    ],
  },
  {
    id: 'help',
    label: 'Help',
    items: ['quickRef', 'shortcuts', 'packageDocs', '-', 'learnLatex', 'ctan', 'texSE', '-', 'website'],
  },
  {
    id: 'about',
    label: 'About',
    items: ['about', 'developer', 'website', '-', 'license', 'notices'],
  },
];
